# Generated by Django 4.1.4 on 2022-12-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='PortfolioApp/images/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
