# Generated by Django 4.1.5 on 2023-01-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0002_techstack_project_created_at_alter_project_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='techs_tack',
        ),
        migrations.AddField(
            model_name='project',
            name='techs_tack',
            field=models.ManyToManyField(to='PortfolioApp.techstack'),
        ),
    ]
