# Generated by Django 4.1.5 on 2023-01-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0004_alter_project_options_alter_techstack_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techstack',
            name='icon_svg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
